apiVersion: v1
kind: ConfigMap
metadata:
  name: realfake-config
  namespace: realfake
data:
  APP_ENV: production
  APP_HOST: 0.0.0.0
  APP_PORT: "8000"
  LOG_LEVEL: INFO
  METRICS_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"
  NEXT_PUBLIC_API_BASE_URL: /api/v1
