apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: realfake-frontend-hpa
  namespace: realfake
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realfake-frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
