apiVersion: v1
kind: ConfigMap
metadata:
  name: realfake-prometheus-config
  namespace: realfake
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: realfake-backend
        metrics_path: /api/v1/admin/metrics
        static_configs:
          - targets: ['realfake-backend:8000']
