"""Application-wide constants for backend API layer."""

from __future__ import annotations

APP_VERSION = "1.0.0"
API_V1_PREFIX = "/api/v1"
REQUEST_ID_HEADER = "X-Request-ID"
DEFAULT_REQUEST_ID = "unknown-request"

DEFAULT_ALLOWED_ARCHIVE_EXTENSIONS = {".zip"}
MAX_FILENAME_LENGTH = 255
MAX_PATH_PART_LENGTH = 200

REPORT_INDEX_FILENAME = "report_index.json"
DEFAULT_REPORT_EXPIRY_SECONDS = 60 * 60 * 24 * 7

ERROR_CODE_UNKNOWN = "UNKNOWN_ERROR"
ERROR_CODE_VALIDATION = "VALIDATION_ERROR"
ERROR_CODE_AUTH = "AUTH_ERROR"
ERROR_CODE_RATE_LIMIT = "RATE_LIMIT_ERROR"
ERROR_CODE_FILE_TOO_LARGE = "FILE_TOO_LARGE"
ERROR_CODE_UNSUPPORTED_FILE = "UNSUPPORTED_FILE_TYPE"
ERROR_CODE_MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
ERROR_CODE_INFERENCE = "INFERENCE_ERROR"
ERROR_CODE_EXPLAINABILITY = "EXPLAINABILITY_ERROR"
ERROR_CODE_REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
